#!/bin/sh
set -e

if [ $# -lt 2 ]; then
    echo 'release <current> <next>'
    echo 'release 1.0 1.1'
    exit 0
fi

mvn clean package
mvn versions:set -DnewVersion=$1
git commit -am "release version $1"
git tag v$1

mvn clean package

mvn versions:set -DnewVersion=$2-SNAPSHOT
git commit -am "next version $2-SNAPSHOT"
git push
git push --tags

